### ISSUE TITLE
Flatten() at /multimodal_representation/multimodal/models/base_models/layers.py: x.view() won't work because of contiguity.

### ISSUE THREAD

**Issue by heyzude** [stanford-iprl-lab/multimodal_representation#4]
Traceback (most recent call last):
  File "mini_main.py", line 37, in <module>
    trainer.train()
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/trainers/selfsupervised.py", line 121, in train
    loss, mm_feat, results, image_packet = self.loss_calc(sample_batched)
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/trainers/selfsupervised.py", line 249, in loss_calc
    image, force, proprio, depth, action
  File "/home/haeju/ambidexserializable/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/models/sensor_fusion.py", line 261, in forward
    action_in,
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/models/sensor_fusion.py", line 115, in forward_encoder
    img_out, img_out_convs = self.img_encoder(image)
  File "/home/haeju/ambidexserializable/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/models/base_models/encoders.py", line 97, in forward
    flattened = self.flatten(out_img_conv6)
  File "/home/haeju/ambidexserializable/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/haeju/ambidexserializable/multimodal_representation/multimodal/models/base_models/layers.py", line 76, in forward
    return x.view(x.size(0), -1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

you can change to reshape I think

**Comment by amichlee** [comment]
Thanks, fixed
